#!/bin/bash

HERE="${BASH_SOURCE%/*}"

. "${HOME}/Cardano/plutus-pioneer-program-me/hc-cardano.env"

cardano-node run                                         \
  --topology      "${HERE}"/config/testnet-topology.json \
  --database-path "${HC_CARDANO_NODE_DB}"                \
  --socket-path   "${CARDANO_NODE_SOCKET_PATH}"          \
  --host-addr     "${HC_CARDANO_NODE_HOST_ADDR}"         \
  --port          "${HC_CARDANO_NODE_PORT=3001}"         \
  --config        "${HERE}"/config/testnet-config.json
