#!/bin/bash

HERE="${BASH_SOURCE%/*}"

. "${HOME}/Cardano/plutus-pioneer-program-me/cardano.env"

cardano-node run                                         \
  --topology      "${HERE}"/config/testnet-topology.json \
  --database-path "${C}"/cardano-node-db                 \
  --socket-path   "${CARDANO_NODE_SOCKET_PATH}"          \
  --host-addr     127.0.0.1                              \
  --port          3001                                   \
  --config        "${HERE}"/config/testnet-config.json
